### ISSUE TITLE
Error on loading plugin

### ISSUE THREAD

**Issue by winfried-van-loon** [jaredmoody/sublime_html_to_text#2]
Hello there! When loading the plugin, I've got an error in the console and the commands are not showing up in the command palette. Is there any plugin of somekind I should install before being able to use this package?

I've pasted the console output below.

```
reloading plugin HTML2Text.html2text
reloading plugin HTML2Text.html2text_plugin
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "./importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/home/xaro/.config/sublime-text-3/Packages/HTML2Text/html2text_plugin.py", line 2, in <module>
    import sublime_html_to_text.html2text
ImportError: No module named 'sublime_html_to_text'
```

I'm currently using Sublime Text 3, build 3066 on Ubuntu 14.04 (LTS), 64-bit.

Thank you in advance!

**Comment by jaredmoody** [comment]
Did you install via package control? I think there might be an issue there.

If so, can you try uninstalling and cloning and let me know if that works?

**Comment by jaredmoody** [comment]
Nevermind, I found the issue and just pushed a fix.
